# keycloak/themes/secure-files/login/theme.properties
parent=base
import=common/keycloak
favIcon=img/favicon.ico
favIconType=image/x-icon

styles=css/styles.css

envBannerRealms=${env.KC_ENV_BANNER_REALMS:}
envBannerLabel=${env.KC_ENV_BANNER_LABEL:DEVELOPMENT}